name: Python application CD
##
on:
  push:
    tags:
      - 'ci-success-*'

permissions:
  contents: read

jobs:
  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: evach28/mlopsproject:latest

      - name: Deploy to production
        run: |
          # Télécharger la nouvelle version de l'image Docker
          docker pull evach28/mlopsproject:latest
          # Démarrer le conteneur Docker dans l'environnement de production
          docker run -d --name mlops_app -p 8080:8080 evach28/mlopsproject:latest
          docker restart mlops_app || true