name: cml workflow
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: CML Run
        env:
            REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          streamlit run source/App/app.py
          # Generate report.md file here
          echo "Report" > report.md
          # Add CML report
          cml comment create --file report.md