name: Download Kaggle Dataset and Push to Dev

on:
  workflow_run:
    workflows: ["Download Kaggle Dataset"]
    types:
      - completed
    branches: 
      - feature_retrieve_data
    statuses:
      - success

permissions:
  contents: write

jobs:
  download_dataset:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: 'dev'
        token: ${{ secrets.GT_TOKEN }}

    - name: Merge feature branch into dev
      run: |
        git merge --no-ff ${{ github.event.workflow_run.head_branch }} -m "Merge feature_retrieve_data into dev"
        git push origin dev

  push_to_dev:
    runs-on: ubuntu-latest
    needs: download_dataset
    steps:
    - name: Checkout dev branch
      uses: actions/checkout@v2
      with:
        ref: 'dev'
        token: ${{ secrets.GT_TOKEN }}

    - name: Push changes to dev branch
      run: |
        git push origin dev
