name: Deploy to Docker Hub

# on:
#     # push:
#     #     branches:
#     #       - streamlit_app

#   repository_dispatch:
#     types: [retrieve_data-completed]

on:
    workflow_run:
      workflows: ["retrieve_data"]
      types: 
        - completed
jobs:
  deploy_the_app_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
            context: .
            push: true
            tags: evach28/mlopsproject:latest