name: Download Kaggle Dataset

on:
  push:
    branches:
      - main
      - streamlit_app  
      # a enleverrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
      #rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr
permissions:
  contents: write
jobs:
  download_dataset:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GT_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        if [ -d "dataset" ]; then
          echo "Deleting existing dataset directory"
          rm -rf dataset
        fi
        mkdir dataset
        kaggle datasets download -d mmmarchetti/transfusion-dataset -p dataset
        unzip dataset/transfusion-dataset.zip -d dataset
        rm dataset/transfusion-dataset.zip

    - name: Run pytest
      run: |
        pytest source/unit_test.py
    - name: Set local Git identity
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit and push changes
      run: |
        git add dataset/*
        if git diff --staged --quiet; then
          echo "No changes in the dataset, skipping commit and push."
        else
          git commit -m "Add dataset"
          git push
        fi
    
    - name: Trigger deployment
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GT_TOKEN }}
        repository: evach28/mlopsproject
        event-type: retrieve-data-completed



    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: Joseph2505/Dev-ML_OPS:latest